server:
  port: 8080
spring:
  redis:
    database: 0
    host: 192.168.59.132
    port: 6379
    password:
    timeout: 5000
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最小空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100000
  mvc:
    dispatch-options-request: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.59.132:3306/wlw?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC
  mail:
    host: smtp.qq.com
    username: 1519696648@qq.com
    default-encoding: utf-8
    password: wpcqqvxgwkujgfdj
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true

mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml

jwt:
  header: "Authorization" #token返回头部
  tokenPrefix: "Bearer " #token前缀
  secret: "741852huhkhiuhi" #密钥
  expireTime: 7200 #token有效时间 (分钟) 建议一小时以上

# 分页插件
pagehelper:
  helperDialect: mysql
  reasonable: false
  params: count=countSql
  supportMethodsArguments: true

mqtt:
  host: tcp://192.168.59.132:1883
  userName: admin
  passWord: admin
  qos: 1
  clientId: admin
  timeout: 10
  keepalive: 20
  topic: $platform/data_bus/data_upload
  topic1: $platform/client_status/client_connected
  topic2: $platform/client_status/client_disconnected
mq:
  ip: 192.168.59.132